FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    curl \
    tar \
    git \
    make \
    jq \
    && rm -rf /var/lib/apt/lists/*

# Install Go
RUN curl -L https://go.dev/dl/go1.22.3.linux-amd64.tar.gz | tar xvzf - -C /usr/local/
ENV PATH="/usr/local/go/bin:${PATH}"

# Install foundry
RUN curl -L https://foundry.paradigm.xyz | bash
ENV PATH="${PATH}:/root/.foundry/bin"
RUN foundryup

WORKDIR /go/astraeus-api-node
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

# Set environment variables from build arguments
ENV TA_STORE_CONTRACT_ADDRESS=${TA_STORE_CONTRACT_ADDRESS}
ENV PRIVATE_KEY=${PRIVATE_KEY}
ENV RPC_URL=${RPC_URL}
RUN chmod 755 ./scripts/docker/*.sh
